// Generated by GitHub Copilot - Sep-08-2026
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// GitHub Pages cannot send custom response headers, so the policy is delivered as a
// meta tag. Injected on build only: the dev server relies on an inline react-refresh
// preamble that a strict script-src would block.
const CSP =
  "default-src 'self'; script-src 'self'; style-src 'self' https://fonts.googleapis.com; " +
  "img-src 'self' data:; media-src 'self'; font-src 'self' https://fonts.gstatic.com; " +
  "connect-src 'self'; form-action 'none'; frame-ancestors 'none'; " +
  "base-uri 'none'; object-src 'none'; upgrade-insecure-requests";

/** Injects security-related meta tags into the built index.html. */
function securityHeaders() {
  return {
    name: 'inject-security-meta',
    apply: 'build',
    transformIndexHtml() {
      return [
        { tag: 'meta', attrs: { 'http-equiv': 'Content-Security-Policy', content: CSP }, injectTo: 'head' },
        { tag: 'meta', attrs: { name: 'referrer', content: 'strict-origin-when-cross-origin' }, injectTo: 'head' },
      ];
    },
  };
}

// For a GitHub Pages *project* site the app is served from https://<user>.github.io/<repo>/,
// so the base path must match the repository name. The deploy workflow injects VITE_BASE.
// For a *user* site (<user>.github.io repo) leave VITE_BASE unset or set it to "/".
export default defineConfig({
  base: process.env.VITE_BASE ?? '/',
  plugins: [react(), securityHeaders()],
  build: {
    target: 'es2020',
    // Smaller payload => less bandwidth and energy per visit.
    cssCodeSplit: true,
    reportCompressedSize: false,
  },
});
