// Generated by GitHub Copilot - Sep-08-2026
import { useEffect, useState } from 'react';

/**
 * Tracks which section is currently in view.
 *
 * Uses IntersectionObserver (event-driven) instead of scroll polling to avoid
 * busy-waiting and unnecessary layout reads on every frame.
 *
 * @param {string[]} ids - Section element ids, in document order.
 * @returns {string} The id of the section considered active.
 */
export default function useActiveSection(ids) {
  const [active, setActive] = useState(ids[0]);

  useEffect(() => {
    const elements = ids
      .map((id) => document.getElementById(id))
      .filter(Boolean);

    if (elements.length === 0) return undefined;

    const visible = new Map();
    const observer = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          visible.set(entry.target.id, entry.isIntersecting ? entry.intersectionRatio : 0);
        }
        let best = null;
        let bestRatio = 0;
        for (const [id, ratio] of visible) {
          if (ratio > bestRatio) {
            best = id;
            bestRatio = ratio;
          }
        }
        if (best) setActive(best);
      },
      { rootMargin: '-20% 0px -55% 0px', threshold: [0, 0.25, 0.5, 1] }
    );

    elements.forEach((el) => observer.observe(el));
    return () => observer.disconnect(); // explicit cleanup: no leaked observers
  }, [ids]);

  return active;
}
