// Generated by GitHub Copilot - Sep-08-2026
import { profile, skills } from '../data/portfolio.js';

/** Landing block shown above the first content section. */
export default function Hero() {
  const stack = skills.find((group) => group.id === 'lang');

  return (
    <section id="top" className="hero" aria-labelledby="hero-heading">
      <h1 id="hero-heading">{profile.name}</h1>
      <p className="hero__role">{profile.role}</p>
      <p className="hero__tagline">{profile.tagline}</p>
      <ul className="hero__stack" aria-label="Core languages">
        {stack.items.map((item) => (
          <li key={item}>{item}</li>
        ))}
      </ul>
    </section>
  );
}
