// Generated by GitHub Copilot - Sep-08-2026
import { useEffect, useRef, useState } from 'react';

const SLIDE_MS = 3500;

/**
 * Interest tile: a cross-fading photo slideshow that flips to a short description on
 * hover, keyboard focus or tap.
 *
 * Green software: the slideshow timer only runs while the tile is on screen, and images
 * below the fold are lazy-loaded.
 * Accessibility: the flip is state-driven so it also fires on keyboard focus, the timer
 * is disabled for users who prefer reduced motion, and photos are decorative.
 *
 * @param {{ interest: { id: string, name: string, description: string, images: string[] } }} props
 */
export default function InterestCard({ interest }) {
  const [flipped, setFlipped] = useState(false);
  const [index, setIndex] = useState(0);
  const cardRef = useRef(null);

  const images = interest.images ?? [];

  useEffect(() => {
    const card = cardRef.current;
    if (!card || images.length < 2) return undefined;
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return undefined;

    let timer = null;
    const stop = () => {
      if (timer) clearInterval(timer);
      timer = null;
    };

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting && !timer) {
          timer = setInterval(() => setIndex((i) => (i + 1) % images.length), SLIDE_MS);
        } else if (!entry.isIntersecting) {
          stop();
        }
      },
      { threshold: 0.25 },
    );

    observer.observe(card);
    return () => {
      stop();
      observer.disconnect();
    };
  }, [images.length]);

  return (
    <li
      ref={cardRef}
      className={flipped ? 'tile is-flipped' : 'tile'}
      onMouseEnter={() => setFlipped(true)}
      onMouseLeave={() => setFlipped(false)}
      onFocus={() => setFlipped(true)}
      onBlur={(event) => {
        if (!event.currentTarget.contains(event.relatedTarget)) setFlipped(false);
      }}
    >
      <div className="tile__inner">
        <div className="tile__face tile__face--front" aria-hidden="true">
          {images.length ? (
            images.map((image, i) => (
              <img
                key={image}
                className={i === index ? 'tile__media tile__slide is-active' : 'tile__media tile__slide'}
                src={`${import.meta.env.BASE_URL}${image}`}
                alt=""
                loading="lazy"
                decoding="async"
              />
            ))
          ) : (
            <span className="tile__placeholder" />
          )}
          <span className="tile__caption">{interest.name}</span>
        </div>

        <div className="tile__face tile__face--back">
          <h3 className="tile__title">{interest.name}</h3>
          <p className="tile__description">{interest.description}</p>
        </div>
      </div>
    </li>
  );
}
