// Generated by GitHub Copilot - Sep-08-2026
import { useEffect, useRef, useState } from 'react';

/**
 * Project tile that shows a looping, muted demo video and flips to the written
 * description on hover, keyboard focus or tap.
 *
 * Green software: preload="none" plus an IntersectionObserver means a clip is only
 * downloaded and decoded while its card is on screen, and playback stops as soon as it
 * scrolls away or the card is flipped.
 * Accessibility: the flip is state-driven so it also fires on keyboard focus, playback
 * is suppressed for users who prefer reduced motion, and the description stays in the
 * DOM for assistive technology.
 *
 * @param {{ project: { id: string, name: string, description: string, tech: string[], video: string|null, repo: string|null, demo: string|null } }} props
 */
export default function ProjectCard({ project }) {
  const [flipped, setFlipped] = useState(false);
  const videoRef = useRef(null);
  const cardRef = useRef(null);

  const src = project.video ? `${import.meta.env.BASE_URL}${project.video}` : null;

  useEffect(() => {
    const card = cardRef.current;
    const video = videoRef.current;
    if (!card || !video) return undefined;
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return undefined;

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          video.play().catch(() => {
            /* Autoplay can be blocked by the browser; a still frame is an acceptable fallback. */
          });
        } else {
          video.pause();
        }
      },
      { threshold: 0.25 },
    );

    observer.observe(card);
    return () => observer.disconnect();
  }, [src]);

  const flip = (next) => {
    setFlipped(next);
    if (next) videoRef.current?.pause();
    else videoRef.current?.play().catch(() => {});
  };

  return (
    <li
      ref={cardRef}
      className={flipped ? 'tile is-flipped' : 'tile'}
      onMouseEnter={() => flip(true)}
      onMouseLeave={() => flip(false)}
      onFocus={() => flip(true)}
      onBlur={(event) => {
        if (!event.currentTarget.contains(event.relatedTarget)) flip(false);
      }}
    >
      <div className="tile__inner">
        <div className="tile__face tile__face--front" aria-hidden="true">
          {src ? (
            <video
              ref={videoRef}
              className="tile__media"
              src={src}
              muted
              loop
              playsInline
              preload="none"
              tabIndex={-1}
            />
          ) : (
            <span className="tile__placeholder" />
          )}
          <span className="tile__caption">{project.name}</span>
        </div>

        <div className="tile__face tile__face--back">
          <h3 className="tile__title">{project.name}</h3>
          <p className="tile__description">{project.description}</p>
          <ul className="tags" aria-label={`Technologies used in ${project.name}`}>
            {project.tech.map((tech) => (
              <li key={tech} className="tag">
                {tech}
              </li>
            ))}
          </ul>
          <p className="tile__links">
            {project.repo ? (
              <a href={project.repo} target="_blank" rel="noopener noreferrer">
                Source
                <span className="visually-hidden"> code for {project.name} (opens in a new tab)</span>
              </a>
            ) : null}
            {project.demo ? (
              <a href={project.demo} target="_blank" rel="noopener noreferrer">
                Live demo
                <span className="visually-hidden"> of {project.name} (opens in a new tab)</span>
              </a>
            ) : null}
          </p>
        </div>
      </div>
    </li>
  );
}
