// Generated by GitHub Copilot - Sep-08-2026
import { useEffect, useRef, useState } from 'react';

const SLIDE_MS = 6000;

/**
 * Research tile: a slideshow of demo media that flips to the write-up on hover,
 * keyboard focus or tap.
 *
 * Green software: media is only fetched and played while the tile is on screen, and
 * images are lazy-loaded.
 * Accessibility: the front face is inert and hidden from assistive technology, the
 * timer is skipped for users who prefer reduced motion, and the flip side carries the
 * links to the repository and the full interactive plot.
 *
 * @param {{ item: { id: string, title: string, meta: string, description: string, tech: string[], media: string[], plot: string|null, repo: string|null } }} props
 */
export default function ResearchCard({ item }) {
  const [flipped, setFlipped] = useState(false);
  const [index, setIndex] = useState(0);
  const [visible, setVisible] = useState(false);
  const cardRef = useRef(null);
  const videoRefs = useRef(new Map());

  const media = item.media ?? [];
  const plotUrl = item.plot ? `${import.meta.env.BASE_URL}${item.plot}` : null;
  const isVideo = (path) => path.toLowerCase().endsWith('.mp4');

  useEffect(() => {
    const card = cardRef.current;
    if (!card) return undefined;

    const observer = new IntersectionObserver(([entry]) => setVisible(entry.isIntersecting), {
      threshold: 0.25,
    });
    observer.observe(card);
    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    if (!visible || media.length < 2) return undefined;
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return undefined;

    const timer = setInterval(() => setIndex((i) => (i + 1) % media.length), SLIDE_MS);
    return () => clearInterval(timer);
  }, [visible, media.length]);

  // Only the on-screen clip plays, so hidden slides cost no bandwidth or decode time.
  useEffect(() => {
    videoRefs.current.forEach((video, path) => {
      if (visible && media[index] === path) video.play().catch(() => {});
      else video.pause();
    });
  }, [index, visible, media]);

  return (
    <li
      ref={cardRef}
      className={flipped ? 'tile is-flipped' : 'tile'}
      onMouseEnter={() => setFlipped(true)}
      onMouseLeave={() => setFlipped(false)}
      onFocus={() => setFlipped(true)}
      onBlur={(event) => {
        if (!event.currentTarget.contains(event.relatedTarget)) setFlipped(false);
      }}
    >
      <div className="tile__inner">
        <div className="tile__face tile__face--front" aria-hidden="true">
          {media.length ? (
            media.map((path, i) => {
              const video = isVideo(path);
              const className = [
                'tile__media',
                'tile__slide',
                video ? '' : 'tile__media--contain',
                i === index ? 'is-active' : '',
              ]
                .filter(Boolean)
                .join(' ');
              const src = `${import.meta.env.BASE_URL}${path}`;
              return video ? (
                <video
                  key={path}
                  ref={(node) => {
                    if (node) videoRefs.current.set(path, node);
                    else videoRefs.current.delete(path);
                  }}
                  className={className}
                  src={src}
                  muted
                  loop
                  playsInline
                  preload="none"
                  tabIndex={-1}
                />
              ) : (
                <img key={path} className={className} src={src} alt="" loading="lazy" decoding="async" />
              );
            })
          ) : (
            <span className="tile__placeholder" />
          )}
          <span className="tile__caption">{item.title}</span>
        </div>

        <div className="tile__face tile__face--back">
          <h3 className="tile__title">{item.title}</h3>
          <p className="tile__meta">{item.meta}</p>
          <p className="tile__description">{item.description}</p>
          <ul className="tags" aria-label={`Technologies used in ${item.title}`}>
            {item.tech.map((tech) => (
              <li key={tech} className="tag">
                {tech}
              </li>
            ))}
          </ul>
          <p className="tile__links">
            {item.repo ? (
              <a href={item.repo} target="_blank" rel="noopener noreferrer">
                Source
                <span className="visually-hidden"> code for {item.title} (opens in a new tab)</span>
              </a>
            ) : null}
            {plotUrl ? (
              <a href={plotUrl} target="_blank" rel="noopener noreferrer">
                Interactive 3D embedding plot
                <span className="visually-hidden"> (opens in a new tab)</span>
              </a>
            ) : null}
          </p>
        </div>
      </div>
    </li>
  );
}
