// Generated by GitHub Copilot - Sep-08-2026
/**
 * Landmark wrapper for a page section.
 *
 * Accessibility: the section is labelled by its own heading, so assistive tech
 * announces "Experience region" rather than an unnamed region.
 *
 * @param {{ id: string, title: string, children: React.ReactNode }} props
 */
export default function Section({ id, title, children }) {
  const headingId = `${id}-heading`;
  return (
    <section id={id} className="section" aria-labelledby={headingId} tabIndex={-1}>
      <h2 id={headingId} className="section__title">
        {title}
      </h2>
      {children}
    </section>
  );
}
