// Generated by GitHub Copilot - Sep-08-2026
import { profile, certificates, experience, education, interests, projects, research, skills, socials } from '../data/portfolio.js';
import Section from './Section.jsx';
import ProjectCard from './ProjectCard.jsx';
import InterestCard from './InterestCard.jsx';
import ResearchCard from './ResearchCard.jsx';

/** Reverse-chronological work history. */
export function Experience() {
  return (
    <Section id="experience" title="Experience">
      <ol className="timeline">
        {experience.map((job) => (
          <li key={job.id} className="timeline__item">
            <h3 className="timeline__title">
              {job.role} <span className="timeline__at">— {job.company}</span>
            </h3>
            <p className="timeline__meta">{job.period}</p>
            <p>{job.summary}</p>
            <ul className="bullets">
              {job.highlights.map((point) => (
                <li key={point}>{point}</li>
              ))}
            </ul>
            <ul className="tags" aria-label={`Technologies used at ${job.company}`}>
              {job.tech.map((tech) => (
                <li key={tech} className="tag">
                  {tech}
                </li>
              ))}
            </ul>
          </li>
        ))}
      </ol>
    </Section>
  );
}

/** Research and publications. */
export function Research() {
  return (
    <Section id="research" title="Research">
      <ul className="tiles">
        {research.map((item) => (
          <ResearchCard key={item.id} item={item} />
        ))}
      </ul>
    </Section>
  );
}

/** Academic background. */
export function Education() {
  return (
    <Section id="education" title="Education">
      <ol className="timeline">
        {education.map((item) => (
          <li key={item.id} className="timeline__item">
            <h3 className="timeline__title">{item.degree}</h3>
            <p className="timeline__meta">
              {item.school} · {item.period}
            </p>
            <p>{item.details}</p>
          </li>
        ))}
      </ol>
    </Section>
  );
}

/**
 * Project tiles: demo video on the front, details on the flip side.
 *
 * Security: outbound links are opened with rel="noopener noreferrer".
 */
export function Projects() {
  return (
    <Section id="projects" title="Projects">
      <ul className="tiles">
        {projects.map((project) => (
          <ProjectCard key={project.id} project={project} />
        ))}
      </ul>
      <p className="tiles__hint">Hover or focus a tile to read about the project.</p>
    </Section>
  );
}

/** Professional certifications and courses. */
export function Certifications() {
  return (
    <Section id="certifications" title="Certifications">
      <ul className="bullets bullets--top">
        {certificates.map((certificate) => (
          <li key={certificate.id}>{certificate.name}</li>
        ))}
      </ul>
    </Section>
  );
}

/** Grouped skill lists. */
export function Skills() {
  return (
    <Section id="skills" title="Skills">
      <div className="skills">
        {skills.map((group) => (
          <div key={group.id} className="skills__group">
            <h3 className="skills__heading">{group.group}</h3>
            <ul className="tags">
              {group.items.map((item) => (
                <li key={item} className="tag">
                  {item}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </Section>
  );
}

/** Personal interests outside work. */
export function Interests() {
  return (
    <Section id="interests" title="Interests">
      <ul className="tiles">
        {interests.map((interest) => (
          <InterestCard key={interest.id} interest={interest} />
        ))}
      </ul>
    </Section>
  );
}

/** Contact details and profile links. */
export function Contact() {
  return (
    <Section id="contact" title="Contact">
      <div className="prose">
        <p>
          The quickest way to reach me is email — or find me on the profiles linked in the
          side rail.
        </p>
        <p>
          <a href={`mailto:${profile.email}`}>{profile.email}</a>
        </p>
        <ul className="contact__links">
          {socials
            .filter((social) => social.id !== 'email')
            .map((social) => (
              <li key={social.id}>
                <a href={social.url} target="_blank" rel="noopener noreferrer">
                  {social.label}
                  <span className="visually-hidden"> (opens in a new tab)</span>
                </a>
              </li>
            ))}
        </ul>
      </div>
    </Section>
  );
}
