// Generated by GitHub Copilot - Sep-08-2026
import { socials } from '../data/portfolio.js';
import { socialIcons } from './Icons.jsx';

/**
 * Fixed vertical rail of external profile links (GitHub, LinkedIn, email).
 *
 * Security: external links use rel="noopener noreferrer" to prevent reverse-tabnabbing
 * and referrer leakage.
 * Accessibility: each link has a visible tooltip label plus an accessible name, and
 * "opens in a new tab" is announced to screen reader users.
 */
export default function SideNav() {
  return (
    <nav className="sidenav" aria-label="Profiles and contact">
      <ul>
        {socials.map((social) => {
          const Icon = socialIcons[social.id];
          const external = !social.url.startsWith('mailto:');
          return (
            <li key={social.id}>
              <a
                href={social.url}
                target={external ? '_blank' : undefined}
                rel={external ? 'noopener noreferrer' : undefined}
              >
                {Icon ? <Icon /> : null}
                <span className="sidenav__label">{social.label}</span>
                <span className="visually-hidden">
                  {social.label}
                  {external ? ' (opens in a new tab)' : ''}
                </span>
              </a>
            </li>
          );
        })}
      </ul>
    </nav>
  );
}
