// Generated by GitHub Copilot - Sep-08-2026
import { useState } from 'react';
import { sections } from '../data/portfolio.js';

/**
 * Sticky top navigation with in-page anchors.
 *
 * Accessibility: real <a href="#id"> links so the page works without JS, keyboard
 * focus and browser history behave natively, and the current section is exposed
 * via aria-current. The mobile toggle is a real <button> with aria-expanded.
 *
 * @param {{ activeId: string }} props
 */
export default function TopNav({ activeId }) {
  const [open, setOpen] = useState(false);

  return (
    <header className="topnav">
      <button
        type="button"
        className="topnav__toggle"
        aria-expanded={open}
        aria-controls="primary-navigation"
        onClick={() => setOpen((v) => !v)}
      >
        <span className="visually-hidden">
          {open ? 'Close navigation menu' : 'Open navigation menu'}
        </span>
        <span className="topnav__burger" aria-hidden="true" />
      </button>

      <nav
        id="primary-navigation"
        aria-label="Sections"
        className={open ? 'topnav__nav is-open' : 'topnav__nav'}
      >
        <ul>
          {sections.map((section) => (
            <li key={section.id}>
              <a
                href={`#${section.id}`}
                aria-current={activeId === section.id ? 'true' : undefined}
                onClick={() => setOpen(false)}
              >
                {section.label}
              </a>
            </li>
          ))}
        </ul>
      </nav>
    </header>
  );
}
