// Generated by GitHub Copilot - Sep-08-2026
import { useMemo } from 'react';
import TopNav from './components/TopNav.jsx';
import SideNav from './components/SideNav.jsx';
import Hero from './components/Hero.jsx';
import {
  Certifications,
  Contact,
  Education,
  Experience,
  Interests,
  Projects,
  Research,
  Skills,
} from './components/Sections.jsx';
import { profile, sections } from './data/portfolio.js';
import useActiveSection from './hooks/useActiveSection.js';

/** Root layout: one scrollable page with a top section nav and a right-hand profile rail. */
export default function App() {
  const ids = useMemo(() => sections.map((section) => section.id), []);
  const activeId = useActiveSection(ids);

  return (
    <>
      <a className="skip-link" href="#main">
        Skip to main content
      </a>
      <TopNav activeId={activeId} />
      <SideNav />
      <main id="main">
        <Hero />
        <Projects />
        <Research />
        <Experience />
        <Education />
        <Certifications />
        <Skills />
        <Interests />
        <Contact />
      </main>
      <footer className="footer">
        <p>
          © {new Date().getFullYear()} {profile.name}. Built with React and Vite.
        </p>
      </footer>
    </>
  );
}
